/**
 * Liste des pays couverts par Reloadly (§ Airtime/Data — Reloadly opère dans
 * le monde entier, pas seulement les 14 pays UEMOA/CEMAC utilisés pour les
 * comptes MobilePay). Codes ISO 3166-1 alpha-2 + noms français.
 */
export const WORLD_COUNTRIES: { code: string; name: string }[] = [
  { code: 'CI', name: "Côte d'Ivoire" }, { code: 'SN', name: 'Sénégal' }, { code: 'ML', name: 'Mali' },
  { code: 'BF', name: 'Burkina Faso' }, { code: 'BJ', name: 'Bénin' }, { code: 'TG', name: 'Togo' },
  { code: 'NE', name: 'Niger' }, { code: 'GW', name: 'Guinée-Bissau' }, { code: 'CM', name: 'Cameroun' },
  { code: 'GA', name: 'Gabon' }, { code: 'CG', name: 'Congo' }, { code: 'TD', name: 'Tchad' },
  { code: 'CF', name: 'République Centrafricaine' }, { code: 'GQ', name: 'Guinée Équatoriale' },
  { code: 'DZ', name: 'Algérie' }, { code: 'AO', name: 'Angola' }, { code: 'BW', name: 'Botswana' },
  { code: 'BI', name: 'Burundi' }, { code: 'CV', name: 'Cap-Vert' }, { code: 'KM', name: 'Comores' },
  { code: 'CD', name: 'RD Congo' }, { code: 'DJ', name: 'Djibouti' }, { code: 'EG', name: 'Égypte' },
  { code: 'ER', name: 'Érythrée' }, { code: 'SZ', name: 'Eswatini' }, { code: 'ET', name: 'Éthiopie' },
  { code: 'GM', name: 'Gambie' }, { code: 'GH', name: 'Ghana' }, { code: 'GN', name: 'Guinée' },
  { code: 'KE', name: 'Kenya' }, { code: 'LS', name: 'Lesotho' }, { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libye' }, { code: 'MG', name: 'Madagascar' }, { code: 'MW', name: 'Malawi' },
  { code: 'MR', name: 'Mauritanie' }, { code: 'MU', name: 'Maurice' }, { code: 'MA', name: 'Maroc' },
  { code: 'MZ', name: 'Mozambique' }, { code: 'NA', name: 'Namibie' }, { code: 'NG', name: 'Nigeria' },
  { code: 'RW', name: 'Rwanda' }, { code: 'ST', name: 'Sao Tomé-et-Principe' }, { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' }, { code: 'SO', name: 'Somalie' }, { code: 'ZA', name: 'Afrique du Sud' },
  { code: 'SS', name: 'Soudan du Sud' }, { code: 'SD', name: 'Soudan' }, { code: 'TZ', name: 'Tanzanie' },
  { code: 'TN', name: 'Tunisie' }, { code: 'UG', name: 'Ouganda' }, { code: 'ZM', name: 'Zambie' },
  { code: 'ZW', name: 'Zimbabwe' },
  { code: 'US', name: 'États-Unis' }, { code: 'CA', name: 'Canada' }, { code: 'MX', name: 'Mexique' },
  { code: 'BR', name: 'Brésil' }, { code: 'AR', name: 'Argentine' }, { code: 'CO', name: 'Colombie' },
  { code: 'PE', name: 'Pérou' }, { code: 'CL', name: 'Chili' }, { code: 'VE', name: 'Venezuela' },
  { code: 'EC', name: 'Équateur' }, { code: 'GT', name: 'Guatemala' }, { code: 'CU', name: 'Cuba' },
  { code: 'DO', name: 'Rép. Dominicaine' }, { code: 'HT', name: 'Haïti' }, { code: 'BO', name: 'Bolivie' },
  { code: 'PY', name: 'Paraguay' }, { code: 'UY', name: 'Uruguay' }, { code: 'JM', name: 'Jamaïque' },
  { code: 'TT', name: 'Trinité-et-Tobago' },
  { code: 'FR', name: 'France' }, { code: 'DE', name: 'Allemagne' }, { code: 'GB', name: 'Royaume-Uni' },
  { code: 'IT', name: 'Italie' }, { code: 'ES', name: 'Espagne' }, { code: 'PT', name: 'Portugal' },
  { code: 'BE', name: 'Belgique' }, { code: 'NL', name: 'Pays-Bas' }, { code: 'CH', name: 'Suisse' },
  { code: 'AT', name: 'Autriche' }, { code: 'SE', name: 'Suède' }, { code: 'NO', name: 'Norvège' },
  { code: 'DK', name: 'Danemark' }, { code: 'FI', name: 'Finlande' }, { code: 'PL', name: 'Pologne' },
  { code: 'IE', name: 'Irlande' }, { code: 'GR', name: 'Grèce' }, { code: 'RO', name: 'Roumanie' },
  { code: 'CZ', name: 'Tchéquie' }, { code: 'HU', name: 'Hongrie' }, { code: 'UA', name: 'Ukraine' },
  { code: 'RU', name: 'Russie' }, { code: 'TR', name: 'Turquie' },
  { code: 'CN', name: 'Chine' }, { code: 'IN', name: 'Inde' }, { code: 'JP', name: 'Japon' },
  { code: 'KR', name: 'Corée du Sud' }, { code: 'ID', name: 'Indonésie' }, { code: 'PH', name: 'Philippines' },
  { code: 'VN', name: 'Vietnam' }, { code: 'TH', name: 'Thaïlande' }, { code: 'MY', name: 'Malaisie' },
  { code: 'SG', name: 'Singapour' }, { code: 'PK', name: 'Pakistan' }, { code: 'BD', name: 'Bangladesh' },
  { code: 'LK', name: 'Sri Lanka' }, { code: 'NP', name: 'Népal' }, { code: 'MM', name: 'Myanmar' },
  { code: 'KH', name: 'Cambodge' }, { code: 'LA', name: 'Laos' },
  { code: 'SA', name: 'Arabie Saoudite' }, { code: 'AE', name: 'Émirats Arabes Unis' }, { code: 'QA', name: 'Qatar' },
  { code: 'KW', name: 'Koweït' }, { code: 'IQ', name: 'Irak' }, { code: 'IR', name: 'Iran' },
  { code: 'IL', name: 'Israël' }, { code: 'JO', name: 'Jordanie' }, { code: 'LB', name: 'Liban' },
  { code: 'OM', name: 'Oman' }, { code: 'YE', name: 'Yémen' }, { code: 'AF', name: 'Afghanistan' },
  { code: 'AU', name: 'Australie' }, { code: 'NZ', name: 'Nouvelle-Zélande' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée' }, { code: 'FJ', name: 'Fidji' },
];
